language: ruby

git:
  submodules: false

env:
  global:
  - AWS_DEFAULT_REGION=ap-southeast-1
  
before_install:
  - echo "Installing AWS CLI"
  - pip install --upgrade --user awscli
  - echo "Installing test gems"
  - gem install yaml-lint

install: true

script:
#   - aws cloudformation validate-template --template-body file://lambda-serverless.yml
  - yaml-lint lambda-serverless.yml

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation template validated"
  - echo "YAML linted"
