version: 0.2

phases:
  install:
    commands:
      #- rm package-lock.json
      - npm install --silent --progress=false -g npm
      
      ## Dependencies
      - npm install --silent --progress-false
      - npm --version
      - npm install --silent --progress=false -g serverless
      # - npm install --silent --save–dev serverless-stack-output
      
  build:
    commands:
      ## Integration test environment
      #- serverless deploy --stage test -v
      - mkdir -p artifacts/dev
      - serverless package --package artifacts/dev --stage dev -v

  post_build:
    commands:
      ## Remove integration testing environment
      #- serverless remove --stage test -v

artifacts:
 files:
   - artifacts/**/*
   - serverless.yml
   - deploy.sh
   - package.json
   - package-lock.json